### ISSUE TITLE
Traditional Chinese version

### ISSUE THREAD

**Issue by zzzace2000** [qipeng/phd-grind-chn#2]
Hi,

Can you provide traditional chinese version?
Your translation is really great and I want to recommend to my family.
Thanks!

**Comment by qipeng** [comment]
I've added a newer commit and the compiled PDF file can be found [here](https://github.com/qipeng/phd-grind-chn/blob/master/phd-grind-chn-trad.pdf).

I simply used an automated simplified-to-traditional converter (specifically, the `mafan` package in Python). This is probably far from perfect, because one simplified character sometimes map to multiple traditional ones depending on the context, and speakers from Hong Kong, Macau, and Taiwan have different translations for certain phrases / words. But hopefully this is better than nothing, and any contribution is welcome!
